clear;
setup = setupGlobals();
reFetch( setup );

data_file = fullfile( setup.DirMegaplotData, 'fetchedVTstringsPlus.mat' );
load( data_file );



idWant1 = strcmpi( vtstrings.What, "VT string" );
idWant = idWant1;
%idWant2 = strcmpi( vtstrings.What, "mini VT string" );
%idWant = idWant1 | idWant2;
vtstrings = vtstrings( idWant,:);

ns = height( vtstrings );

% Sort

fprintf( "%4s  %-13s  %-22s %8s   %4s  %4s  %4s  %4s  %3s    %7s   %7s   %3s  %3s  %8s  %3s  %4s  %4s\n", ...
    "N", "ID", "What", "Dur(m)", "nTot", "nLoc", "nM>2", "nM>3", "ML", "Moment", "MomRate", ...
    "Act", "Rpt", "Purity", "Frm", "1st", "MSS1" );

for is = 1:ns

    str = sprintf( "%4d  %13s  %-22s %8.2f   %4d  %4d  %4d  %4d   %3.1f   %7.2f   %7.2f   %-3s  %-3s  %-8s  %-3s  %-4s  %-4s\n", ...
        is, ...
        string( vtstrings.ID(is) ), ...
        string( vtstrings.What(is) ), ...
        vtstrings.Duration(is), ...
        vtstrings.NevTotal(is), ...
        vtstrings.NevLocated(is), ...
        vtstrings.NevM2plus(is), ...
        vtstrings.NevM3plus(is), ...
        vtstrings.MaxML(is), ...
        vtstrings.Moment(is)/1.0e+12, ...
        vtstrings.MomentRate(is)/1.0e+12, ...
        string( vtstrings.Activity(is) ), ...
        string( vtstrings.Repeating(is) ), ...
        string( vtstrings.Purity(is) ), ...
        string( vtstrings.Form(is) ), ...
        string( vtstrings.FirstSta(is) ), ...
        string( vtstrings.MSS1(is) ) );
    str = strrep(str, 'NaN', ' - ');
    fprintf( '%s', str);

end